config/routes.rb
# frozen_string_literal: true

GeoblacklightAdmin::Engine.routes.draw do
  # GBL‡ADMIN
  resources :bulk_actions do
    patch :run, on: :member
    patch :revert, on: :member
  end

  # @TODO - Users
  # devise_for :users, skip: [:registrations]
  # as :user do
  #  get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
  #  get "/sign_up" => "devise/registrations#new", :as => "new_user_registration" # custom path to sign_up/registration
  #  get "users/edit" => "devise/registrations#edit", :as => "edit_user_registration"
  #  put "users" => "devise/registrations#update", :as => "user_registration"
  # end

  namespace :admin do
    # Root
    root to: "documents#index"

    # Bulk Actions
    resources :bulk_actions do
      patch :run, on: :member
      patch :revert, on: :member
    end

    # Imports
    resources :imports do
      resources :mappings
      resources :import_documents, only: [:show]
      patch :run, on: :member
    end

    # Elements
    resources :elements do
      post :sort, on: :collection
    end

    # Reference Types
    resources :reference_types do
      post :sort, on: :collection
    end

    # Form Elements
    resources :form_elements do
      post :sort, on: :collection
    end
    resources :form_header, path: :form_elements, controller: :form_elements
    resources :form_group, path: :form_elements, controller: :form_elements
    resources :form_control, path: :form_elements, controller: :form_elements
    resources :form_feature, path: :form_elements, controller: :form_elements

    # Notifications
    resources :notifications do
      put "batch", on: :collection
    end

    # Users
    get "users/index"

    # Bookmarks
    resources :bookmarks
    delete "/bookmarks", to: "bookmarks#destroy", as: :bookmarks_destroy_by_fkeys

    # AdvancedSearch controller
    get "/advanced_search" => "advanced_search#index", :constraints => ->(req) { req.format == :json }
    get "/advanced_search/facets" => "advanced_search#facets", :constraints => ->(req) { req.format == :json }
    get "/advanced_search/facet/:id" => "advanced_search#facet", :constraints => lambda { |req|
                                                                                   req.format == :json
                                                                                 }, :as => "advanced_search_facet"

    # Ids controller
    get "/api/ids" => "ids#index", :constraints => ->(req) { req.format == :json }
    get "/api" => "api#index", :constraints => ->(req) { req.format == :json }
    get "/api/fetch" => "api#fetch", :constraints => ->(req) { req.format == :json }
    get "/api/facet/:id" => "api#facet", :constraints => ->(req) { req.format == :json }

    resources :documents do
      get "versions"
      get "admin"

      resources :document_licensed_accesses, path: "licensed_access" do
        collection do
          get "import"
          post "import"
          get "destroy_all"
          post "destroy_all"
        end
      end

      resources :document_assets, path: "assets" do
        collection do
          get "display_attach_form"
          post "attach_files"

          get "destroy_all"
          post "destroy_all"
        end
      end

      resources :document_downloads, path: "downloads" do
        collection do
          get "import"
          post "import"

          get "destroy_all"
          post "destroy_all"
        end
      end

      resources :document_references, path: "references" do
        collection do
          get "display_attach_form"
          post "attach_files"

          get "import"
          post "import"

          get "destroy_all"
          post "destroy_all"
        end
      end
    end

    resources :document_licensed_accesses, path: "licensed_access" do
      collection do
        get "import"
        post "import"
        get "destroy_all"
        post "destroy_all"
      end
    end

    resources :document_assets, path: "assets" do
      collection do
        get "display_attach_form"
        post "attach_files"

        get "destroy_all"
        post "destroy_all"
      end
    end

    get "/documents/:id/ingest", to: "document_assets#display_attach_form", as: "asset_ingest"
    post "/documents/:id/ingest", to: "document_assets#attach_files"
    # mount Kithe::AssetUploader.upload_endpoint(:cache) => "/direct_upload", :as => :direct_app_upload

    resources :collections, except: [:show]

    # Note "assets" is Rails reserved word for routing, oops. So we use
    # asset_files.
    resources :assets, path: "asset_files", except: %i[new create] do
      member do
        put "convert_to_child_work"
      end
    end

    # @TODO
    # mount Qa::Engine => "/authorities"
    mount ActionCable.server => "/cable"

    # @TODO
    # authenticate :user, ->(user) { user } do
    # mount Blazer::Engine, at: "blazer"
    # end
  end
end

app/controllers/geoblacklight_admin/document_accesses_controller.rb
# frozen_string_literal: true

# GeoblacklightAdmin::DocumentAccessesController
module GeoblacklightAdmin
  class DocumentAccessesController < GeoblacklightAdmin::AdminController
    before_action :set_document
    before_action :set_document_access, only: %i[show edit update destroy]

    # GET /documents/#id/access
    # GET /documents/#id/access.json
    def index
      if params[:document_id]
        @document_accesses = DocumentAccess.where(friendlier_id: @document.friendlier_id).order(institution_code: :asc)
      else
        @pagy, @document_accesses = pagy(DocumentAccess.all.order(friendlier_id: :asc, updated_at: :desc), items: 20)
      end
    end

    # GET /document_accesses/1
    # GET /document_accesses/1.json
    def show
    end

    # GET /document_accesses/new
    def new
      @document_access = DocumentAccess.new
    end

    # GET /document_accesses/1/edit
    def edit
    end

    # POST /document_accesses
    # POST /document_accesses.json
    def create
      @document_access = DocumentAccess.new(document_access_params)
      logger.debug("DA Params: #{DocumentAccess.new(document_access_params).inspect}")
      logger.debug("Document ACCESS: #{@document_access.inspect}")

      respond_to do |format|
        if @document_access.save
          format.html do
            redirect_to admin_document_document_accesses_path(@document), notice: "Document access was successfully created."
          end
          format.json { render :show, status: :created, location: @document_access }
        else
          format.html { render :new }
          format.json { render json: @document_access.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /document_accesses/1
    # PATCH/PUT /document_accesses/1.json
    def update
      respond_to do |format|
        if @document_access.update(document_access_params)
          format.html do
            redirect_to admin_document_document_accesses_path(@document), notice: "Document access was successfully updated."
          end
          format.json { render :show, status: :ok, location: @document_access }
        else
          format.html { render :edit }
          format.json { render json: @document_access.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /document_accesses/1
    # DELETE /document_accesses/1.json
    def destroy
      @document_access.destroy
      respond_to do |format|
        format.html do
          redirect_to admin_document_document_accesses_path(@document), notice: "Document access was successfully destroyed."
        end
        format.json { head :no_content }
      end
    end

    def destroy_all
      logger.debug("Destroy Access Links")
      return unless params.dig(:document_access, :assets, :file)

      respond_to do |format|
        if DocumentAccess.destroy_all(params.dig(:document_access, :assets, :file))
          format.html { redirect_to document_accesses_path, notice: "Document Access Links were created destroyed." }
        else
          format.html { redirect_to document_accesses_path, notice: "Document Access Links could not be destroyed." }
        end
      rescue => e
        format.html { redirect_to document_accesses_path, notice: "Document Access Links could not be destroyed. #{e}" }
      end
    end

    # GET   /documents/#id/access/import
    # POST  /documents/#id/access/import
    def import
      logger.debug("Import Action")
      return unless params.dig(:document_access, :assets, :file)

      respond_to do |format|
        if DocumentAccess.import(params.dig(:document_access, :assets, :file))
          format.html { redirect_to document_accesses_path, notice: "Document access links were created successfully." }
        else
          format.html { redirect_to document_accesses_path, notice: "Access URLs could not be created." }
        end
      rescue => e
        format.html { redirect_to document_accesses_path, notice: "Access URLs could not be created. #{e}" }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_document
      return unless params[:document_id] # If not nested

      @document = Document.includes(:leaf_representative).find_by!(friendlier_id: params[:document_id])
    end

    def set_document_access
      @document_access = DocumentAccess.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def document_access_params
      params.require(:document_access).permit(:friendlier_id, :institution_code, :access_url)
    end
  end
end

app/views/admin/document_accesses/import.html.erb
<p id="notice"><%= notice %></p>

<h1 style="width:100%; border-bottom:dotted;" class="mb-4">
  Document &middot; Institutional Access
  <% if params[:document_id] %>
    <%= link_to '+ New Access URL', new_admin_document_document_access_path(@document), { class: 'btn btn-primary float-right' } %>
  <% end %>
</h1>

<div class="row">
  <div class="col-6">
    <% if params[:document_id] %>
      <h2 class='h3'><%= @document.title %></h2>
    <% else %>
      <h2 class='h3'>Import for Multiple Documents</h2>
    <% end %>

    <p class="alert alert-info" role="alert">
      <strong>Note:</strong> New Institutional Access URLs will be created. Existing Institutional Access URLs will be updated per the CSV file.
    </p>

    <h3 class='h4'>Upload a CSV File</h3>
    <%= simple_form_for DocumentAccess.new, url: import_admin_document_accesses_path, method: :post, multipart: true do |f| %>
      <div class="form-inputs">
        <%= f.simple_fields_for :assets do |asset_fields| %>
          <%= asset_fields.input :file, as: :file, input_html: {} %>
        <%- end %>
      </div>

      <div class="form-actions">
        <%= submit_tag "+ Import CSV", {class: 'btn btn-primary'} %>
      </div>
    <% end %>
  </div>
  <div class="col-6">
    <h4>Example CSV File</h4>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>friendlier_id</th>
          <th>institution_code</th>
          <th>access_url</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>999-0010</td>
          <td>12</td>
          <td>http://pi.lib.uchicago.edu/1001/cat/bib/11538549</td>
        </tr>
        <tr>
          <td>999-0010-alabama</td>
          <td>12</td>
          <td>http://pi.lib.uchicago.edu/1001/cat/bib/11538549</td>
        </tr>
        <tr>
          <td>...</td>
          <td>...</td>
          <td>...</td>
        </tr>
      </tbody>
    </table>

    <h5>CSV File Column Definitions</h5>
    <dl>
      <dt>friendlier_id</dt>
      <dd>The associated GEOMG document's friendlier id</dd>
      <dt>institution_code</dt>
      <dd>The <a target="_blank" href="https://github.com/geobtaa/geomg/blob/be1b6ac6628bd8f537ab10ecb88e5f4804540e2b/app/helpers/application_helper.rb#L28-L44">code</a> for the institution</dd>
      <dt>access_url</dt>
      <dd>The URL for the Access link</dd>
    </dl>
  </div>
</div>