config/routes.rb
# frozen_string_literal: true

GeoblacklightAdmin::Engine.routes.draw do
  # GBL‡ADMIN
  resources :bulk_actions do
    patch :run, on: :member
    patch :revert, on: :member
  end

  # @TODO - Users
  # devise_for :users, skip: [:registrations]
  # as :user do
  #  get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
  #  get "/sign_up" => "devise/registrations#new", :as => "new_user_registration" # custom path to sign_up/registration
  #  get "users/edit" => "devise/registrations#edit", :as => "edit_user_registration"
  #  put "users" => "devise/registrations#update", :as => "user_registration"
  # end

  namespace :admin do
    # Root
    root to: "documents#index"

    # Bulk Actions
    resources :bulk_actions do
      patch :run, on: :member
      patch :revert, on: :member
    end

    # Imports
    resources :imports do
      resources :mappings
      resources :import_documents, only: [:show]
      patch :run, on: :member
    end

    # Elements
    resources :elements do
      post :sort, on: :collection
    end

    # Reference Types
    resources :reference_types do
      post :sort, on: :collection
    end

    # Form Elements
    resources :form_elements do
      post :sort, on: :collection
    end
    resources :form_header, path: :form_elements, controller: :form_elements
    resources :form_group, path: :form_elements, controller: :form_elements
    resources :form_control, path: :form_elements, controller: :form_elements
    resources :form_feature, path: :form_elements, controller: :form_elements

    # Notifications
    resources :notifications do
      put "batch", on: :collection
    end

    # Users
    get "users/index"

    # Bookmarks
    resources :bookmarks
    delete "/bookmarks", to: "bookmarks#destroy", as: :bookmarks_destroy_by_fkeys

    # AdvancedSearch controller
    get "/advanced_search" => "advanced_search#index", :constraints => ->(req) { req.format == :json }
    get "/advanced_search/facets" => "advanced_search#facets", :constraints => ->(req) { req.format == :json }
    get "/advanced_search/facet/:id" => "advanced_search#facet", :constraints => lambda { |req|
                                                                                   req.format == :json
                                                                                 }, :as => "advanced_search_facet"

    # Ids controller
    get "/api/ids" => "ids#index", :constraints => ->(req) { req.format == :json }
    get "/api" => "api#index", :constraints => ->(req) { req.format == :json }
    get "/api/fetch" => "api#fetch", :constraints => ->(req) { req.format == :json }
    get "/api/facet/:id" => "api#facet", :constraints => ->(req) { req.format == :json }

    resources :documents do
      get "versions"
      get "admin"

      resources :document_licensed_accesses, path: "licensed_access" do
        collection do
          get "import"
          post "import"
          get "destroy_all"
          post "destroy_all"
        end
      end

      resources :document_assets, path: "assets" do
        collection do
          get "display_attach_form"
          post "attach_files"

          get "destroy_all"
          post "destroy_all"
        end
      end

      resources :document_downloads, path: "downloads" do
        collection do
          get "import"
          post "import"

          get "destroy_all"
          post "destroy_all"
        end
      end

      resources :document_references, path: "references" do
        collection do
          get "display_attach_form"
          post "attach_files"

          get "import"
          post "import"

          get "destroy_all"
          post "destroy_all"
        end
      end
    end

    resources :document_licensed_accesses, path: "licensed_access" do
      collection do
        get "import"
        post "import"
        get "destroy_all"
        post "destroy_all"
      end
    end

    resources :document_assets, path: "assets" do
      collection do
        get "display_attach_form"
        post "attach_files"

        get "destroy_all"
        post "destroy_all"
      end
    end

    get "/documents/:id/ingest", to: "document_assets#display_attach_form", as: "asset_ingest"
    post "/documents/:id/ingest", to: "document_assets#attach_files"
    # mount Kithe::AssetUploader.upload_endpoint(:cache) => "/direct_upload", :as => :direct_app_upload

    resources :collections, except: [:show]

    # Note "assets" is Rails reserved word for routing, oops. So we use
    # asset_files.
    resources :assets, path: "asset_files", except: %i[new create] do
      member do
        put "convert_to_child_work"
      end
    end

    # @TODO
    # mount Qa::Engine => "/authorities"
    mount ActionCable.server => "/cable"

    # @TODO
    # authenticate :user, ->(user) { user } do
    # mount Blazer::Engine, at: "blazer"
    # end
  end
end

app/controllers/admin/document_assets_controller.rb
# frozen_string_literal: true

# Admin::DocumentAssetsController
#
# This controller manages the document assets within the admin namespace.
# It provides actions to list, show, edit, update, destroy, and attach files
# to document assets.
#
# Before Actions:
# - set_document: Sets the document based on the document_id parameter.
# - set_document_asset: Sets the document asset based on the id parameter for specific actions.
module Admin
  class DocumentAssetsController < Admin::AdminController
    before_action :set_document
    before_action :set_document_asset, only: %i[show edit update destroy]

    # GET /admin/document_assets
    #
    # Lists all document assets. If a document_id is provided, it filters
    # the assets by the specified document.
    def index
      scope = Asset

      # simple simple search on a few simple attributes with OR combo.
      if params[:document_id].present?
        document = Document.find_by_friendlier_id(params[:document_id])
        scope = scope.where(parent_id: document.id)
      end

      # scope = scope.page(params[:page]).per(20).order(created_at: :desc)
      scope = scope.includes(:parent)

      @document_assets = scope
    end

    # GET /admin/document_assets/:id
    #
    # Shows a specific document asset. If the asset is stored, it also
    # retrieves the fixity checks associated with the asset.
    def show
      @asset = Asset.find_by_friendlier_id!(params[:id])

      return unless @asset.stored?

      @checks = @asset.fixity_checks.order("created_at asc")
      @latest_check = @checks.last
      @earliest_check = @checks.first
    end

    # GET /admin/document_assets/:id/edit
    #
    # Renders the edit form for a specific document asset.
    def edit
    end

    # PATCH/PUT /admin/document_assets/:id
    #
    # Updates a specific document asset. If successful, redirects to the
    # document assets index with a success notice. Otherwise, re-renders
    # the edit form with errors.
    def update
      @document_asset = Asset.find_by_friendlier_id!(params[:id])

      respond_to do |format|
        if @document_asset.update(document_asset_params)
          format.html { redirect_to admin_document_document_assets_path(@document), notice: "Asset was successfully updated." }
          format.json { render :show, status: :ok, location: @document_asset }
        else
          format.html { render :edit }
          format.json { render json: @document_asset.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admin/document_assets/:id
    #
    # Destroys a specific document asset. Redirects to the document assets
    # index with a success notice.
    def destroy
      @asset = Asset.find_by_friendlier_id!(params[:id])
      @asset.destroy

      respond_to do |format|
        format.html do
          redirect_to admin_document_document_assets_path(@document),
            notice: "Asset '#{@asset.title}' was successfully destroyed."
        end
        format.json { head :no_content }
      end
    end

    # GET /admin/document_assets/display_attach_form
    #
    # Displays the form to attach files to a document.
    def display_attach_form
      @document = Document.find_by_friendlier_id!(params[:document_id])
    end

    # POST /document/:id/ingest
    #
    # Attaches files to a document. Receives JSON hashes for direct uploaded
    # files in params[:files] and creates filesets for them.
    def attach_files
      @parent = Document.find_by_friendlier_id!(params[:id])

      current_position = @parent.members.maximum(:position) || 0

      files_params = (params[:cached_files] || [])
        .collect { |s| JSON.parse(s) }
        .sort_by { |h| h&.dig("metadata", "filename") }

      files_params.each do |file_data|
        asset = Asset.new

        # if derivative_storage_type = params.dig(:storage_type_for, file_data["id"])
        #  asset.derivative_storage_type = derivative_storage_type
        # end

        # References
        references = params.dig(:dct_references_for, file_data["id"])
        asset.dct_references_uri_key = references if references

        asset.position = (current_position += 1)
        asset.parent_id = @parent.id
        asset.file = file_data
        asset.title = (asset.file&.original_filename || "Untitled")
        asset.save!
      end

      @parent.update(representative: @parent.members.order(:position).first) if @parent.representative_id.nil?

      redirect_to admin_document_document_assets_path(@parent.friendlier_id, anchor: "nav-members")
    end

    private

    # Strong parameters for asset.
    #
    # Returns a list of permitted parameters for asset creation and update.
    def asset_params
      allowed_params = [:title, :derivative_storage_type, :alt_text, :caption,
        :transcription, :english_translation,
        :role, {admin_note_attributes: []}, :dct_references_for]
      allowed_params << :published if can?(:publish, @asset)
      params.require(:asset).permit(*allowed_params)
    end

    # Sets the document based on the document_id parameter.
    #
    # If the document_id is not present, it does nothing.
    def set_document
      return unless params[:document_id] # If not nested

      @document = Document.includes(:leaf_representative).find_by!(friendlier_id: params[:document_id])
    end

    # Sets the document asset based on the id parameter.
    def set_document_asset
      @document_asset = DocumentAsset.find_by_friendlier_id(params[:id])
    end

    # Strong parameters for document asset.
    #
    # Returns a list of permitted parameters for document asset update.
    def document_asset_params
      params.require(:asset).permit(:parent_id, :title, :label, :dct_references_uri_key, :thumbnail)
    end
  end
end

app/controllers/geoblacklight_admin/document_assets_controller.rb
# frozen_string_literal: true

# GeoblacklightAdmin::DocumentAssetsController
module GeoblacklightAdmin
  class DocumentAssetsController < GeoblacklightAdmin::AdminController
    before_action :set_document

    def index
      scope = Kithe::Asset

      # simple simple search on a few simple attributes with OR combo.
      if params[:document_id].present?
        document = Document.find_by_friendlier_id(params[:document_id])
        scope = scope.where(parent_id: document.id)
      end

      # scope = scope.page(params[:page]).per(20).order(created_at: :desc)
      scope = scope.includes(:parent)

      @document_assets = scope
    end

    def show
      @asset = Kithe::Asset.find_by_friendlier_id!(params[:id])
      authorize! :read, @asset

      return unless @asset.stored?

      @checks = @asset.fixity_checks.order("created_at asc")
      @latest_check = @checks.last
      @earliest_check = @checks.first
    end

    def edit
      @asset = Kithe::Asset.find_by_friendlier_id!(params[:id])
      authorize! :update, @asset
    end

    # PATCH/PUT /works/1
    # PATCH/PUT /works/1.json
    def update
      @asset = Kithe::Asset.find_by_friendlier_id!(params[:id])
      authorize! :update, @asset

      respond_to do |format|
        if @asset.update(asset_params)
          format.html { redirect_to admin_asset_url(@asset), notice: "Asset was successfully updated." }
          format.json { render :show, status: :ok, location: @asset }
        else
          format.html { render :edit }
          format.json { render json: @asset.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @asset = Kithe::Asset.find_by_friendlier_id!(params[:id])
      @asset.destroy

      respond_to do |format|
        format.html do
          redirect_to document_document_assets_path(@document),
            notice: "Asset '#{@asset.title}' was successfully destroyed."
        end
        format.json { head :no_content }
      end
    end

    def check_fixity
      @asset = Kithe::Asset.find_by_friendlier_id!(params[:asset_id])
      SingleAssetCheckerJob.perform_later(@asset)
      redirect_to admin_asset_url(@asset), notice: "This file will be checked shortly."
    end

    def fixity_report
      @fixity_report = FixityReport.new
    end

    def display_attach_form
      @document = Document.find_by_friendlier_id!(params[:document_id])
    end

    # Receives json hashes for direct uploaded files in params[:files],
    # and id in params[:id] (friendlier_id)
    # creates filesets for them and attach.
    #
    # POST /document/:id/ingest
    def attach_files
      @parent = Document.find_by_friendlier_id!(params[:id])

      current_position = @parent.members.maximum(:position) || 0

      files_params = (params[:cached_files] || [])
        .collect { |s| JSON.parse(s) }
        .sort_by { |h| h&.dig("metadata", "filename") }

      files_params.each do |file_data|
        asset = Kithe::Asset.new

        # if derivative_storage_type = params.dig(:storage_type_for, file_data["id"])
        #  asset.derivative_storage_type = derivative_storage_type
        # end

        asset.position = (current_position += 1)
        asset.parent_id = @parent.id
        asset.file = file_data
        asset.title = (asset.file&.original_filename || "Untitled")
        asset.save!
      end

      @parent.update(representative: @parent.members.order(:position).first) if @parent.representative_id.nil?

      redirect_to document_path(@parent.friendlier_id, anchor: "nav-members")
    end

    def convert_to_child_work
      @asset = Kithe::Asset.find_by_friendlier_id!(params[:id])

      parent = @asset.parent

      new_child = Work.new(title: @asset.title)

      # Asking for permission to create a new Work,
      # which is arguably the main thing going on in this method.
      # authorize! :create, Work as the first line of the method
      # would be better, but we currently aren't allowed to do that
      # see (https://github.com/chaps-io/access-granted/pull/56).
      authorize! :create, new_child

      new_child.parent = parent
      # collections
      new_child.contained_by = parent.contained_by
      new_child.position = @asset.position
      new_child.representative = @asset
      # we can copy _all_ the non-title metadata like this...
      new_child.json_attributes = parent.json_attributes

      @asset.parent = new_child

      Kithe::Model.transaction do
        new_child.save!
        @asset.save! # to get new parent

        if parent.representative_id == @asset.id
          parent.representative = new_child
          parent.save!
        end
      end

      redirect_to edit_admin_work_path(new_child), notice: "Asset promoted to child work #{new_child.title}"
    end

    # requires params[:active_encode_status_id]
    def refresh_active_encode_status
      status = ActiveEncodeStatus.find(params[:active_encode_status_id])

      RefreshActiveEncodeStatusJob.perform_later(status)

      redirect_to admin_asset_url(status.asset),
        notice: "Started refresh for ActiveEncode job #{status.active_encode_id}"
    end

    def work_is_oral_history?
      (@asset.parent.is_a? Work) && @asset.parent.genre && @asset.parent.genre.include?("Oral histories")
    end
    helper_method :work_is_oral_history?

    def asset_is_collection_thumbnail?
      @asset.parent.is_a? Collection
    end
    helper_method :asset_is_collection_thumbnail?

    def edit_path(asset)
      asset.parent.is_a? Collection ? edit_admin_collection_path(asset.parent) : edit_admin_asset_path(asset)
    end
    helper_method :edit_path

    def parent_path(asset)
      return nil if asset.parent.nil?

      asset.parent.is_a? Collection ? collection_path(asset.parent) : admin_work_path(asset.parent)
    end
    helper_method :parent_path

    private

    def set_document
      return unless params[:document_id] # If not nested

      @document = Document.includes(:leaf_representative).find_by!(friendlier_id: params[:document_id])
    end

    def asset_params
      allowed_params = [:title, :derivative_storage_type, :alt_text, :caption,
        :transcription, :english_translation,
        :role, {admin_note_attributes: []}]
      allowed_params << :published if can?(:publish, @asset)
      params.require(:asset).permit(*allowed_params)
    end
  end
end

app/views/admin/document_assets/_assets_table.html.erb
<div class="table-responsive">
  <table class="table table-striped table-bordered sortable">
    <thead class="thead-dark">
      <tr>
        <th>Thumbnail</th>
        <th>Preview</th>
        <th>Title</th>
        <th>Label</th>
        <th>File Size</th>
        <th>MimeType</th>
        <th>Reference URI Type</th>
        <th colspan="2">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% document_assets.each do |document_asset| %>
        <tr>
        <td>
          <%= form_with model: document_asset, url: admin_document_document_asset_path(document_asset.parent, document_asset), method: :put, remote: true, class: 'thumbnail-form' do |f| %>
            <%= f.check_box :thumbnail, class: 'thumbnail-toggle', onchange: "this.form.submit()" %>
              <%= f.submit 'Save', class: 'btn btn-sm btn-primary d-none' %>
            <% end %>
          </td>
          <td>
            <% if document_asset.respond_to?(:thumbnail) %>
              <% unless document_asset.file_url(:thumb_standard).nil? %>
                <%= image_tag(document_asset.file_url(:thumb_standard), { height: 100 }) %>
              <% end %>
            <% end %>
          </td>
          <td><%= link_to(document_asset.title, document_asset.file.url) %></td>
          <td><%= document_asset.label %></td>
          <td>
            <%= number_to_human_size(document_asset.file_data["metadata"]["size"]) %>
          </td>
          <td>
            <%= document_asset.file_data["metadata"]["mime_type"] %>
            <span class="sr-only"><%= document_asset.inspect %></span>
          </td>
          <td>
            <%= document_asset.dct_references_uri_key %>
          </td>
          <td>
            <%= link_to 'Edit', edit_admin_document_document_asset_path(document_asset.parent, document_asset) %>
          </td>
          <td>
            <%= link_to 'Destroy', admin_document_document_asset_path(document_asset.parent, document_asset), method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/document_assets/_form.html.erb
<%= simple_form_for [:admin, @document, @document_asset], :url => admin_document_document_asset_path(@document, @document_asset) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= link_to "Parent Document", admin_document_path(@document_asset.parent) %>
    <%= f.input :parent_id, as: :hidden %>
    <%= f.input :title %>
    <%= f.input :label %>
    <%= f.input :dct_references_uri_key, collection: I18n.t("activemodel.enum_values.document/reference.category").invert.sort.insert(0, ["Choose Reference Type", nil]), label: 'Reference' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Save Asset', {class: 'btn btn-primary'} %>
  </div>
<% end %>

app/views/admin/document_assets/display_attach_form.html.erb
<div class="scihist-attach-files">

  <h1>Add Files</h1>
  <h2>To: <%= @document.title %> (<%= @document.friendlier_id %>)</h2>
  <p>Once the files have been uploaded and are ready for attachment, you can proceed to Attach.</p>

  <%= form_with(url: admin_asset_ingest_path(@document && @document.friendlier_id), method: :post, local: true) do |form| %>

    <div class="row">

        <div class="col-md-6 mb-3">
          <h2>1. Upload Files</h2>
          
          <%= content_tag "div", class: "uppy-dashboard-container", data: Admin::UploadUtil.kithe_upload_data_config do %>
          <% end %>
        </div>

        <div class="col-sm-6">
          <h2>2. Attach Files</h2>
          <div class="d-flex justify-content-between">
            <%= form.submit "Attach", class: "btn btn-primary btn-lg", data: { toggle: "kithe-upload-submit" } %>
            <%= link_to  "Cancel", admin_document_path(@document),
                  class: "btn btn-outline-secondary btn-lg",
                  data: { confirm: "Cancel attach files?" }
            %>
          </div>
          <table class="table table-sm mt-3 attach-files-table" data-toggle="cached-files-table">
            <tr>
              <th class="attach-files-table-filename">Filename</th>
              <th class="attach-files-table-size">Size</th>
              <th class="attach-files-table-references">References</th>
              <th class="attach-files-table-remove"></th>
            </tr>
          </table>
        </div>
    </div>

  <% end %>
</div>

app/views/admin/document_assets/edit.html.erb
<h1>Editing Document Asset</h1>

<%= render 'form', document_asset: @document_asset %>

<%= link_to 'Back', admin_document_document_assets_path(@document) %>

app/views/admin/document_assets/index.html.erb
<%- @page_title = "GBL♦Admin - Document - Assets" %>

<div class="row mb-2">
  <div class="col">
    <h1 style="width:100%;">
      Document &middot; Assets

      <% if params[:document_id] %>
        <%= link_to '+ Upload Assets', display_attach_form_admin_document_document_assets_url(@document), { class: 'btn btn-primary float-right mr-2' } %>
      <% end %>
    </h1>
    <% if params[:document_id] %>
      <h2 class='h3'>
        <%= link_to(@document.title, admin_document_path(@document)) %>
        &middot;
        <%= @document_assets.count %> assets 
        &middot;
        <%= number_to_human_size(@document.gbl_fileSize_s) %>
      </h2>
    <% else %>
      <h2 class='h3'>Assets</h2>
    <% end %>

    <% if @pagy %>
    <h6>
      <span class='float-left mt-3'>
        <%== pagy_info(@pagy, 'assets'.pluralize(@pagy.count)) %>
      </span>
      <span class='float-right'>
        <%== pagy_bootstrap_nav(@pagy) %>
      </span>
    </h6>
    <% end %>

    <%= render partial: 'assets_table', locals: { document_assets: @document_assets } %>

      <% if @pagy %>
      <h6>
        <span class='float-left mt-3'>
          <%== pagy_info(@pagy, 'imports'.pluralize(@pagy.count)) %>
        </span>
        <span class='float-right'>
          <%== pagy_bootstrap_nav(@pagy) %>
        </span>
      </h6>
      <% end %>
    </div>
  </div>
</div>