config/routes.rb
# frozen_string_literal: true

GeoblacklightAdmin::Engine.routes.draw do
  # GBL‡ADMIN
  resources :bulk_actions do
    patch :run, on: :member
    patch :revert, on: :member
  end

  # @TODO - Users
  # devise_for :users, skip: [:registrations]
  # as :user do
  #  get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
  #  get "/sign_up" => "devise/registrations#new", :as => "new_user_registration" # custom path to sign_up/registration
  #  get "users/edit" => "devise/registrations#edit", :as => "edit_user_registration"
  #  put "users" => "devise/registrations#update", :as => "user_registration"
  # end

  namespace :admin do
    # Root
    root to: "documents#index"

    # Bulk Actions
    resources :bulk_actions do
      patch :run, on: :member
      patch :revert, on: :member
    end

    # Imports
    resources :imports do
      resources :mappings
      resources :import_documents, only: [:show]
      patch :run, on: :member
    end

    # Elements
    resources :elements do
      post :sort, on: :collection
    end

    # Reference Types
    resources :reference_types do
      post :sort, on: :collection
    end

    # Form Elements
    resources :form_elements do
      post :sort, on: :collection
    end
    resources :form_header, path: :form_elements, controller: :form_elements
    resources :form_group, path: :form_elements, controller: :form_elements
    resources :form_control, path: :form_elements, controller: :form_elements
    resources :form_feature, path: :form_elements, controller: :form_elements

    # Notifications
    resources :notifications do
      put "batch", on: :collection
    end

    # Users
    get "users/index"

    # Bookmarks
    resources :bookmarks
    delete "/bookmarks", to: "bookmarks#destroy", as: :bookmarks_destroy_by_fkeys

    # AdvancedSearch controller
    get "/advanced_search" => "advanced_search#index", :constraints => ->(req) { req.format == :json }
    get "/advanced_search/facets" => "advanced_search#facets", :constraints => ->(req) { req.format == :json }
    get "/advanced_search/facet/:id" => "advanced_search#facet", :constraints => lambda { |req|
                                                                                   req.format == :json
                                                                                 }, :as => "advanced_search_facet"

    # Ids controller
    get "/api/ids" => "ids#index", :constraints => ->(req) { req.format == :json }
    get "/api" => "api#index", :constraints => ->(req) { req.format == :json }
    get "/api/fetch" => "api#fetch", :constraints => ->(req) { req.format == :json }
    get "/api/facet/:id" => "api#facet", :constraints => ->(req) { req.format == :json }

    resources :documents do
      get "versions"
      get "admin"

      resources :document_licensed_accesses, path: "licensed_access" do
        collection do
          get "import"
          post "import"
          get "destroy_all"
          post "destroy_all"
        end
      end

      resources :document_assets, path: "assets" do
        collection do
          get "display_attach_form"
          post "attach_files"

          get "destroy_all"
          post "destroy_all"
        end
      end

      resources :document_downloads, path: "downloads" do
        collection do
          get "import"
          post "import"

          get "destroy_all"
          post "destroy_all"
        end
      end

      resources :document_references, path: "references" do
        collection do
          get "display_attach_form"
          post "attach_files"

          get "import"
          post "import"

          get "destroy_all"
          post "destroy_all"
        end
      end
    end

    resources :document_licensed_accesses, path: "licensed_access" do
      collection do
        get "import"
        post "import"
        get "destroy_all"
        post "destroy_all"
      end
    end

    resources :document_assets, path: "assets" do
      collection do
        get "display_attach_form"
        post "attach_files"

        get "destroy_all"
        post "destroy_all"
      end
    end

    get "/documents/:id/ingest", to: "document_assets#display_attach_form", as: "asset_ingest"
    post "/documents/:id/ingest", to: "document_assets#attach_files"
    # mount Kithe::AssetUploader.upload_endpoint(:cache) => "/direct_upload", :as => :direct_app_upload

    resources :collections, except: [:show]

    # Note "assets" is Rails reserved word for routing, oops. So we use
    # asset_files.
    resources :assets, path: "asset_files", except: %i[new create] do
      member do
        put "convert_to_child_work"
      end
    end

    # @TODO
    # mount Qa::Engine => "/authorities"
    mount ActionCable.server => "/cable"

    # @TODO
    # authenticate :user, ->(user) { user } do
    # mount Blazer::Engine, at: "blazer"
    # end
  end
end

app/models/document_reference.rb
# frozen_string_literal: true

require "csv"

# DocumentReference
#
# This class represents a reference to a document, which includes a URL and a reference type.
# It belongs to a document and a reference type, and it supports CSV import and export.
#
# Associations:
# - belongs_to :document
# - belongs_to :reference_type
#
# Callbacks:
# - after_save :reindex_document
#
# Validations:
# - Validates presence of :friendlier_id, :reference_type_id, :url
# - Validates uniqueness of :url scoped to :friendlier_id and :reference_type_id
#
# Scopes:
# - to_aardvark_references: Converts references to aardvark format
# - to_csv: Converts references to CSV format
class DocumentReference < ApplicationRecord
  belongs_to :document, foreign_key: :friendlier_id, primary_key: :friendlier_id
  belongs_to :reference_type
  after_save :reindex_document

  # Validations
  validates :friendlier_id, :reference_type_id, :url, presence: true
  validates :url, uniqueness: {scope: [:friendlier_id, :reference_type_id]}

  # Scopes
  scope :to_aardvark_references, -> {
    references = where(friendlier_id: pluck(:friendlier_id)).map(&:to_aardvark_reference)
    merged = {}
    references.each do |ref|
      if ref.keys.first == "http://schema.org/downloadUrl"
        merged["http://schema.org/downloadUrl"] ||= []
        merged["http://schema.org/downloadUrl"] << {
          "url" => ref.values.first,
          "label" => ref[:label]
        }
      else
        merged[ref.keys.first] = ref.values.first
      end
    end
    merged
  }
  scope :to_csv, -> { where(friendlier_id: pluck(:friendlier_id)).map(&:to_csv) }

  # CSV Column Names
  #
  # Returns an array of column names for CSV export.
  #
  # @return [Array<String>] the CSV column names
  def self.csv_column_names
    ["friendlier_id", "reference_type", "reference_url", "label"]
  end

  # Import
  #
  # Imports document references from a CSV file.
  #
  # @param file [File] the CSV file to import
  # @return [Boolean] true if import is successful
  def self.import(file)
    logger.debug("CSV Import")
    ::CSV.foreach(file.path, headers: true) do |row|
      logger.debug("CSV Row: #{row.to_hash}")
      document_reference = DocumentReference.find_or_initialize_by(
        friendlier_id: row.to_hash["friendlier_id"],
        reference_type_id: ReferenceType.find_by(name: row.to_hash["reference_type"]).id,
        url: row.to_hash["reference_url"],
        label: row.to_hash["label"]
      )

      logger.debug("Document Reference: #{document_reference.inspect}")

      document_reference.update!(
        friendlier_id: row.to_hash["friendlier_id"],
        reference_type_id: ReferenceType.find_by(name: row.to_hash["reference_type"]).id,
        url: row.to_hash["reference_url"],
        label: row.to_hash["label"]
      )
    end
    true
  end

  # Destroy All
  #
  # Destroys document references based on a CSV file.
  #
  # @param file [File] the CSV file to process
  # @return [Boolean] true if destroy is successful
  def self.destroy_all(file)
    logger.debug("CSV Destroy")
    ::CSV.foreach(file.path, headers: true) do |row|
      logger.debug("CSV Row: #{row.to_hash}")
      if DocumentReference.destroy_by(
        friendlier_id: row.to_hash["friendlier_id"],
        reference_type_id: ReferenceType.find_by(name: row.to_hash["reference_type"]).id,
        url: row.to_hash["reference_url"]
      )
        logger.debug("Destroyed: #{row.to_hash}")
      else
        logger.debug("Not Destroyed: #{row.to_hash}")
      end
    end
    true
  end

  # To CSV
  #
  # Converts the document reference to an array suitable for CSV export.
  #
  # @return [Array<String>] the CSV row data
  def to_csv
    [
      friendlier_id,
      reference_type.name,
      url,
      label
    ]
  end

  # To Aardvark Reference
  #
  # Converts the document reference to an aardvark reference format.
  #
  # @return [Hash] the aardvark reference
  def to_aardvark_reference
    hash = {}
    hash[reference_type.reference_uri.to_s] = url
    hash[:label] = label if reference_type.reference_uri.to_s == "http://schema.org/downloadUrl"
    hash
  end

  # Reindex Document
  #
  # Reindexes the associated document.
  def reindex_document
    document.save
  end
end

app/views/admin/document_references/_form.html.erb
<%= simple_form_for([:admin, @document, @document_reference]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :friendlier_id, input_html: { value: @document.friendlier_id, readonly: true } %>
    <%= f.input :reference_type_id, as: :select, collection: ReferenceType.all.map { |r| [r.reference_type, r.id] }, label: 'Reference Type' %>
    <%= f.input :url, label: 'Reference URL' %>
    <%= f.input :label, autofocus: true, input_html: { disabled: true, id: 'label-input' } %>
    
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Create Download URL', {class: 'btn btn-primary'} %>
  </div>
<% end %>

<script>
document.addEventListener('DOMContentLoaded', function() {
  const referenceSelect = document.querySelector('select[name="document_reference[reference_type_id]"]');
  const labelInput = document.getElementById('label-input');

  function toggleLabelInput() {
    if (referenceSelect.options[referenceSelect.selectedIndex].text === 'Download file') {
      labelInput.disabled = false;
    } else {
      labelInput.disabled = true;
    }
  }

  referenceSelect.addEventListener('change', toggleLabelInput);
    toggleLabelInput(); // Initial check
  });
</script>

app/views/admin/document_references/destroy_all.html.erb
<p id="notice"><%= notice %></p>

<h1 style="width:100%; border-bottom:dotted;" class="mb-4">
  Document &middot; Destroy References
  <% if params[:document_id] %>
    <%= link_to '+ New Reference', new_document_document_reference_path(@document), { class: 'btn btn-primary float-right' } %>
  <% end %>
</h1>

<div class="row">
  <div class="col-4">
    <% if params[:document_id] %>
      <h2 class='h3'><%= @document.title %></h2>
    <% else %>
      <h2 class='h3'>Destroy Multiple References</h2>
    <% end %>

    <p class="alert alert-danger" role="alert">
      <strong>Warning:</strong> All matching References will be destroyed. There is <strong>NO UNDO</strong> here.
    </p>
    <h3 class='h4'>Upload a CSV File</h3>

    <%= simple_form_for DocumentReference.new, url: destroy_all_admin_document_references_path, method: :post, multipart: true do |f| %>
      <div class="form-group">
        <div class="form-inputs">
          <%= f.simple_fields_for :references do |reference_fields| %>
            <%= reference_fields.input :file, as: :file, input_html: {} %>
          <%- end %>
        </div>

        <div class="form-actions">
          <%= submit_tag "- Destroy All", {class: 'btn btn-danger'} %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-8">
    <h4>Example CSV File</h4>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>friendlier_id</th>
          <th>reference_type</th>
          <th>reference_url</th>
          <th>label</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>00add5b8-a7b1-42d4-b4de-ca99716a5096</td>
          <td>download</td>
          <td>https://s3.amazonaws.com/holc/tiles/WI/Madison/1937/rectified.zip</td>
          <td>GeoTIFF</td>
        </tr>
        <tr>
          <td>00add5b8-a7b1-42d4-b4de-ca99716a5096</td>
          <td>download</td>
          <td>https://s3.amazonaws.com/holc/tiles/WI/Madison/1937/holc-scan.jpg</td>
          <td>JPEG</td>
        </tr>
        <tr>
          <td>...</td>
          <td>...</td>
          <td>...</td>
          <td>...</td>
        </tr>
      </tbody>
    </table>

    <h5>CSV File Column Definitions</h5>
    <dl>
      <dt>friendlier_id</dt>
      <dd>The associated document's friendlier id</dd>
      <dt>reference_type</dt>
      <dd>The name of the reference type</dd>
      <dt>reference_url</dt>
      <dd>The URL for the reference</dd>
      <dt>label</dt>
      <dd>The label for the reference, if the reference type is labeled</dd>
    </dl>
  </div>
</div>

app/views/admin/document_references/import.html.erb
<p id="notice"><%= notice %></p>

<h1 style="width:100%; border-bottom:dotted;" class="mb-4">
  Document &middot; References
  <% if params[:document_id] %>
    <%= link_to '+ New Reference', new_admin_document_document_reference_path(@document), { class: 'btn btn-primary float-right' } %>
  <% end %>
</h1>

<div class="row">
  <div class="col-4">
    <% if params[:document_id] %>
      <h2 class='h3'><%= @document.title %></h2>
    <% else %>
      <h2 class='h3'>Import for Multiple Documents</h2>
    <% end %>

    <p class="alert alert-info" role="alert">
      <strong>Note:</strong> New References will be created. Existing References will be updated per the CSV file.
    </p>

    <h3 class="h4">Upload a CSV File</h3>
    <%= simple_form_for DocumentReference.new, url: import_admin_document_references_path, method: :post, multipart: true do |f| %>
      <div class="form-inputs">
        <%= f.simple_fields_for :references do |reference_fields| %>
          <%= reference_fields.input :file, as: :file, input_html: {} %>
        <%- end %>
      </div>

      <div class="form-actions">
        <%= submit_tag "+ Import CSV", {class: 'btn btn-primary'} %>
      </div>
    <% end %>
  </div>
  <div class="col-8">
    <h4>Example CSV File</h4>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>friendlier_id</th>
          <th>reference_type</th>
          <th>reference_url</th>
          <th>label</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>00add5b8-a7b1-42d4-b4de-ca99716a5096</td>
          <td>download</td>
          <td>https://s3.amazonaws.com/holc/tiles/WI/Madison/1937/rectified.zip</td>
          <td>GeoTIFF</td>
        </tr>
        <tr>
          <td>00add5b8-a7b1-42d4-b4de-ca99716a5096</td>
          <td>download</td>
          <td>https://s3.amazonaws.com/holc/tiles/WI/Madison/1937/holc-scan.jpg</td>
          <td>JPEG</td>
        </tr>
        <tr>
          <td>...</td>
          <td>...</td>
          <td>...</td>
          <td>...</td>
        </tr>
      </tbody>
    </table>

    <h5>CSV File Column Definitions</h5>
    <dl>
      <dt>friendlier_id</dt>
      <dd>The associated document's friendlier id</dd>
      <dt>reference_type</dt>
      <dd>The name of the reference type</dd>
      <dt>reference_url</dt>
      <dd>The URL for the reference</dd>
      <dt>label</dt>
      <dd>The label for the reference, if the reference type is labeled</dd>
    </dl>
  </div>
</div>

app/views/admin/document_references/index.html.erb
<%- @page_title = "GBL♦Admin - Document - Download Links" %>

<div class="row mb-2">
  <div class="col">
    <h1 style="width:100%;">
      Document &middot; References

      <% if params[:document_id] %>
        <%= link_to '+ Import CSV', import_admin_document_document_references_path(@document), { class: 'btn btn-primary float-right' } %>

        <%= link_to '+ New Reference', new_admin_document_document_reference_path(@document), { class: 'btn btn-primary float-right mr-2' } %>
      <% else %>
        <%= link_to '- Delete CSV', destroy_all_admin_document_references_path, { class: 'btn btn-danger float-right' } %>
        <%= link_to '+ Import CSV', import_admin_document_references_path, { class: 'btn btn-primary float-right mr-4' } %>
      <% end %>
    </h1>

    <% if params[:document_id] %>
    <h2 class='h3'>
      <%= link_to(@document.title, admin_document_path(@document)) %>
      &middot;
      <%= @document_references.count %> references
    </h2>
    <% else %>
      <h2 class='h3'>References</h2>
    <% end %>

    <!-- Tab navigation -->
    <ul class="nav nav-tabs" id="documentTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="html-tab" data-toggle="tab" href="#html" role="tab" aria-controls="html" aria-selected="true">HTML</a>
      </li>
      <% if params[:document_id] %>
        <li class="nav-item">
          <a class="nav-link" id="json-tab" data-toggle="tab" href="#json" role="tab" aria-controls="json" aria-selected="false">JSON</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="csv-tab" data-toggle="tab" href="#csv" role="tab" aria-controls="csv" aria-selected="false">CSV</a>
        </li>
      <% end %>
    </ul>

    <!-- Tab content -->
    <div class="tab-content" id="documentTabContent">
      <div class="tab-pane fade show active" id="html" role="tabpanel" aria-labelledby="html-tab">
        <br />
        <!-- HTML content -->

        <% if @pagy %>
          <h6>
            <span class='float-left mt-3'>
              <%== pagy_info(@pagy) %>
            </span>
            <span class='float-right'>
              <%== pagy_bootstrap_nav(@pagy) %>
            </span>
          </h6>
        <% end %>

        <% if @document %>
          <h3>External – Document References</h3>
        <% end %>

        <table class="table table-striped table-bordered sortable">
          <thead class="thead-dark">
            <tr>
              <th class="header">Layer Slug</th>
              <th class="header">Type</th>
              <th class="header">URI</th>
              <th class="header">Value</th>
              <th class="header">Label</th>
              <th class="header" colspan="2">Actions</th>
            </tr>
          </thead>

          <tbody>
            <% @document_references.each do |document_reference| %>
              <tr>
                <td><%= link_to document_reference.friendlier_id, admin_document_path(document_reference.document) %></td>
                <td><%= document_reference.reference_type.reference_type %></td>
                <td><%= document_reference.reference_type.reference_uri %></td>
                <td><%= link_to document_reference.url, document_reference.url, target: '_blank' %></td>
                <td><%= document_reference.label %></td>
                <td><%= link_to 'Edit', edit_admin_document_document_reference_path(document_reference.document, document_reference) %></td>
                <td><%= link_to 'Destroy', admin_document_document_reference_path(document_reference.document, document_reference), method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <% if @pagy %>
          <h6>
            <span class='float-left mt-3'>
              <%== pagy_info(@pagy) %>
            </span>
            <span class='float-right'>
              <%== pagy_bootstrap_nav(@pagy) %>
            </span>
          </h6>
        <% end %>

        <% if @document && @document.distributable_assets.any? %>
          <h3>Internal – Distributable Assets</h3>
          <%= render partial: 'admin/document_assets/assets_table', locals: { document_assets: @document.document_assets } %>
        <% end %>
      </div>

      <% if params[:document_id] %>
        <div class="tab-pane fade" id="json" role="tabpanel" aria-labelledby="json-tab">
          <h3 class="mt-4">Ruby Hash</h3>
          <%= ap(@document.references).html_safe %>
          <h3 class="mt-4">JSON</h3>
          <%= ap(@document.references.to_json).html_safe %>
        </div>

        <div class="tab-pane fade" id="csv" role="tabpanel" aria-labelledby="csv-tab">
          <br />

          <!-- CSV content -->
          <table class="table table-striped table-bordered sortable">
          <thead class="thead-dark">
            <tr>
              <th class="header">Layer Slug</th>
              <th class="header">Type</th>
              <th class="header">Value</th>
              <th class="header">Label</th>
            </tr>
          </thead>
          <tbody>
            <% @document.references_csv.each do |row| %>
              <tr>
                <% row.each do |value| %>
                  <td><%= value %></td>
                <% end %>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      <% end %>
    </div>
  </div>
</div>